# called from kernel build system: just declare what our modules are
CFLAGS_MODULE += -I$(INCLUDE) -I$(src) -DCONFIG_WARP -DCONFIG_WARP_DAHDI -DWARP_V2

obj-m := warp_analog.o
warp_analog-objs	:= wa_base.o wa_dma.o wa_common.o power_fail_transfer.o
