// WARNING -- This file is automatically generated by Autobuild.
//            Any changes made will be lost after the next build.

#ifndef PK_SYSTEMVER_H
#define PK_SYSTEMVER_H

#define PikaLoadVerString  "3.0.0.171"
#define PikaLoadMajorNum 3
#define PikaLoadMinorNum 0
#define PikaLoadCustomerRel 0
#define PikaLoadBuildnum 171
#define PikaLoadPatchlevel " "
#define PikaLoadCopyright "Copyright (c) 2009 PIKA Technologies Inc."

#define PikaLoadComment "Standard Build"

#endif
